version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: myonara/webmud3:v0.0.36
    environment: 
      NODE_ENV: 'production'
    # command: --tls-cert=/run/secrets/cert.pem --tls-key=/run/secrets/privkey.pem
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 2018
      restart_policy:
        condition: on-failure
    ports:
      - "2018:5000"
    networks:
      webnet:    
        ipv4_address: 172.16.238.10
  apache:
    image: 'bitnami/apache:2.4'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - '8443:8443'
    volumes:
      - 'apache_data:/bitnami'
    networks:
      webnet:    
        ipv4_address: 172.16.238.11
volumes:
  apache_data:
networks:
  webnet:
    driver: overlay
    attachable: true
