version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: myonara/webmud3:v0.0.9
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "2018:5000"
    networks:
      - webnet
networks:
  webnet: