version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: myonara/webmud3:latest
    environment: 
      NODE_ENV: 'production'
    # command: --tls-cert=/run/secrets/cert.pem --tls-key=/run/secrets/privkey.pem
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 2018
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2 
        window: 3600s
    ports:
      - "2018:5000"
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
    attachable: true
